export const languages = {
  en: {
    
    navbar: {
      home: "Home",
      about: "About Us",
      contact: "Contact",
      language: "Language",
      login: "Login",
      dashboard: "Dashboard",
      logout: "Logout"
    },
    hero: {
      title: 'Find Your Perfect Rental Car',
      subtitle: 'Choose from our wide selection of vehicles',
      search: 'Search Cars',
    },
    footer: {
      description: 'Your best choice for vehicle rentals with the best quality and service.',
      contact: 'Contact',
      follow: 'Follow Us',
      rights: 'All rights reserved.',
    },
    carTypes: {
      economy: 'Economy',
      luxury: 'Luxury',
      suv: 'SUV',
      sports: 'Sports',
    },
    booking: {
      pickupDate: 'Pickup Date',
      returnDate: 'Return Date',
      location: 'Location',
      search: 'Search',
    },
    auth: {
      welcome: "Welcome",
      signupMessage: "Join our amazing community",
      loginMessage: "Login to access the dashboard",
      signupButton: "Sign Up",
      loginButton: "Login",
      emailPlaceholder: "Email",
      passwordPlaceholder: "Password",
      createAccountButton: "Create Account",
      loginButtonSubmit: "Log In",
      continueWith: "Or continue with",
      googleButton: "Google",
      facebookButton: "Facebook",
      logoutButton: "Log Out",
    },
    reservation: {
      assets: "seating",
      title: "Reserve {carBrand} {carModel}",
      price: "Price/day",
      fuel: "Fuel: {fuelType}",
      transmission: "Transmission: {transmission}",
      buyerName: "Buyer's Name",
      email: "Email",
      phone: "Phone Number",
      idType: "ID Type",
      startDate: "Start Date",
      endDate: "End Date",
      paymentMethod: "Payment Method",
      card: "Card",
      transfer: "Bank Transfer",
      cash: "Cash",
      deliveryAddress: "Delivery or Pickup Address",
      additionalNotes: "Additional Notes",
      confirm: "Confirm Reservation",
      cancel: "Cancel"
    },
    filters: {
      carFilters: "Car Filters",
      brand: "Brand",
      selectBrand: "Select Brand",
      model: "Model",
      selectModel: "Select Model",
      pricePerDay: "Price Per Day ($)",
      transmission: "Transmission",
      fuelType: "Fuel Type",
      selectFuelType: "Select Fuel Type",
      available: "Available",
      availableOnly: "Only Available Cars",
      applyFilters: "Apply Filters",
      todas: "All",
      hasta: "Up to",
      noResults: "No results found",
      notAvailable: "Not Available",  // Aquí se agrega la traducción de "Not Available"
      alert:"Please log in to continue.",

    },
    comments: {
      title: "Leave Your Comment",
      commentLabel: "Comment",
      ratingLabel: "Rating (1-5)",
      imageLabel: "Image (optional)",
      submitButton: "Submit Comment",
      submittingButton: "Submitting...",
      loginToComment: "You must be logged in to comment",
      successMessage: "Your comment has been submitted successfully",
      errorMessage: "There was an error submitting your comment",
    },

    about: {
      title: "About Us",
        header: "Your Trusted Car Rental Partner",
        paragraph1: "With over 15 years of experience in the market, we have become leaders in car rentals, offering personalized and high-quality service to all our customers.",
        paragraph2: "Our mission is to provide the best car rental experience, with a modern fleet and exceptional service that exceeds your expectations.",
        paragraph3:"100% Secure",
        paragraph4:"Premium Quality",
        paragraph5:"Fast Service",
        paragraph6:"Awarded",
        description1:"Vehicles insured and certified",
        description2:"State-of-the-art fleet",
        description3:"Simplified rental process",
        description4:"Recognized for our excellence",
  
      },
      
      contact:{
      phone: "Phone",
      hours: "Mon - Sun: 8:00 - 20:00",
      email: "Email",
      location: "Location",
      sendMessage: "Send us a message",
      name: "Name",
      emails: "Email",
      subject: "Subject",
      message: "Message",
      sendButton: "Send Message",
      namePlaceholder: "Your Name",
      emailPlaceholder: "your@email.com",
      subjectPlaceholder: "Subject of the message",
      messagePlaceholder: "Write your message here"
      }

},
  es: {
    navbar: {
      home: "Inicio",
      about: "Sobre Nosotros",
      contact: "Contacto",
      language: "Idioma",
      login: "Iniciar sesión",
      dashboard: "Dashboard",
      logout: "Cerrar sesión"
    },
    reservation: {
      title: "Reservar {carBrand} {carModel}",
      price: "Precio/día",
      fuel: "Combustible: {fuelType}",
      transmission: "Transmisión: {transmission}",
      buyerName: "Nombre del Comprador",
      email: "Correo Electrónico",
      phone: "Número de Teléfono",
      idType: "Tipo de Documento",
      startDate: "Fecha de Inicio",
      endDate: "Fecha de Fin",
      paymentMethod: "Método de Pago",
      card: "Tarjeta",
      transfer: "Transferencia Bancaria",
      cash: "Efectivo",
      deliveryAddress: "Dirección de Entrega o Recogida",
      additionalNotes: "Observaciones Adicionales",
      confirm: "Confirmar Reserva",
      cancel: "Cancelar",
      assets:"asientos",
    },
    hero: {
      title: 'Encuentra Tu Auto Perfecto',
      subtitle: 'Elige de nuestra amplia selección de vehículos',
      search: 'Buscar Autos',
    },
    footer: {
      description: 'Tu mejor opción para alquilar vehículos con la mejor calidad y servicio.',
      contact: 'Contacto',
      follow: 'Síguenos',
      rights: 'Todos los derechos reservados.',
    },
    carTypes: {
      economy: 'Económico',
      luxury: 'Lujo',
      suv: 'SUV',
      sports: 'Deportivo',
    },
    booking: {
      pickupDate: 'Fecha de Recogida',
      returnDate: 'Fecha de Devolución',
      location: 'Ubicación',
      search: 'Buscar',
    },
    auth: {
      welcome: "Bienvenido",
      signupMessage: "Únete a nuestra increíble comunidad",
      loginMessage: "Inicia sesión para acceder al panel",
      signupButton: "Registrarse",
      loginButton: "Iniciar Sesión",
      emailPlaceholder: "Correo electrónico",
      passwordPlaceholder: "Contraseña",
      createAccountButton: "Crear Cuenta",
      loginButtonSubmit: "Iniciar Sesión",
      continueWith: "O continuar con",
      googleButton: "Google",
      facebookButton: "Facebook",
      logoutButton: "Cerrar Sesión",
    },
    filters: {
      carFilters: "Filtros de Autos",
      brand: "Marca",
      selectBrand: "Seleccionar Marca",
      model: "Modelo",
      selectModel: "Seleccionar Modelo",
      pricePerDay: "Precio por Día ($)",
      transmission: "Transmisión",
      fuelType: "Tipo de Combustible",
      selectFuelType: "Seleccionar Combustible",
      available: "Disponible",
      availableOnly: "Solo Autos Disponibles",
      applyFilters: "Aplicar Filtros",
      todas: "Todas",
      hasta: "Hasta",
      noResults: "No se encontraron resultados",
      notAvailable: "No Disponible",  // Aquí se agrega la traducción de "No Disponible"
      alert:"Por favor, inicia sesión para continuar."
    },
    comments: {
      title: "Deja tu Comentario",
      commentLabel: "Comentario",
      ratingLabel: "Calificación (1-5)",
      imageLabel: "Imagen (opcional)",
      submitButton: "Enviar comentario",
      submittingButton: "Enviando...",
      loginToComment: "Debes iniciar sesión para comentar",
      successMessage: "Tu comentario ha sido enviado con éxito",
      errorMessage: "Hubo un error al enviar tu comentario",
    },
    about: {
      title: "Sobre Nosotros",
      header: "Tu Socio de Confianza en Alquiler de Autos",
      paragraph1: "Con más de 15 años de experiencia en el mercado, nos hemos convertido en líderes en el alquiler de vehículos, ofreciendo un servicio personalizado y de calidad a todos nuestros clientes.",
      paragraph2: "Nuestra misión es proporcionar la mejor experiencia de alquiler de autos, con una flota moderna y un servicio excepcional que supere tus expectativas.",
      paragraph3:"100% Seguro",
      paragraph4:"Calidad Premium",
      paragraph5:"Servicio Rápido",
      paragraph6:"Premiados",
      description1:"Vehículos asegurados y certificados",
      description2:"Flota de última generación",
      description3:"Proceso de alquiler simplificado",
      description4:"Reconocidos por nuestra excelencia",
    },
    contact:{
      phone: "Teléfono",
      hours: "Lun - Dom: 8:00 - 20:00",
      email: "Correo Electrónico",
      location: "Ubicación",
      sendMessage: "Envíanos un mensaje",
      name: "Nombre",
      emails: "Correo Electrónico",
      subject: "Asunto",
      message: "Mensaje",
      sendButton: "Enviar Mensaje",
      namePlaceholder: "Tu nombre",
      emailPlaceholder: "tu@email.com",
      subjectPlaceholder: "Asunto del mensaje",
      messagePlaceholder: "Escribe tu mensaje aquí",
    }
  
  },
};
